name: CD

on:
  push:
    paths-ignore:
    - '.github/**'
    - '.git**'
    - '**README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build Joomla Package
      id: jxbuild
      uses: mavrosxristoforos/jxb@1.0
      with:
        build-file: 'build_popfeed.jxb'
    - name: Get XML
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: 'popfeed/popfeed.xml'
        xpath: '//version'
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'popfeed.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.getxml.outputs.info }}
